version: "1.0"
services:
    arangoDB:
        image: "arangodb"
        container_name: "arangodb"
        ports:
            - "8529:8529"
        environment:
            ARANGO_ROOT_PASSWORD: "password"
    neo4j:
        image: "neo4j"
        container_name: "neo4j"
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: "neo4j/neo4jdevops"
        volumes:
            - "C:/Users/Gleb/Desktop/Учеба/Диплом/go-remerge/neo4jdb/data:/data"
            - "C:/Users/Gleb/Desktop/Учеба/Диплом/go-remerge/neo4jdb/import:/var/lib/neo4j/import"
            - "C:/Users/Gleb/Desktop/Учеба/Диплом/go-remerge/neo4jdb/logs:/logs"
            - "C:/Users/Gleb/Desktop/Учеба/Диплом/go-remerge/neo4jdb/plugins:/plugins"


