---
project_name: go-remerge
analysis_name: self-check
source_directory: /home/gleb/win_home/Desktop/Учеба/Диплом/go-remerge
languages:
  - golang
extensions:
  - .go
ignore_directories:
  - .git
  - .idea
  - neo4jdb
  - scripts
  - export
ignore_files:
  - .gitignore
  - go_build_go_remerge_linux
  - token
  - log.json
graphs:
  - graph: filesystem
    direction: directed
export:
  as_file:
    output_dir: /home/gleb/go-remerge/export
    formats:
      - json
      - arango_format
  arango:
    username: root
    password: password
    endpoints:
      - http://localhost:8529
    database: test
  neo4j:
    username: neo4j
    password: neo4jdevops
    uri: neo4j://localhost:7687
