---
project_name: emerge test
analysis_name: check python project analysis
source_directory: C:\Users\Gleb\Desktop\Учеба\Диплом\emerge
languages:
  - python
extensions:
  - .py
ignore_directories:
  - .git
  - .vscode
  - .github
  - output
  - testdata
ignore_files:
  - .gitignore
graphs:
  - graph: filesystem
    direction: directed
  - graph: file_dependency
    direction: directed
  - graph: entity_dependency
    direction: directed
export:
  as_file:
    output_dir: C:\Users\Gleb\Desktop\Учеба\Диплом\go-remerge\export
    formats:
      - json
      - arango_format
  neo4j:
    username: neo4j
    password: neo4jpython
    uri: neo4j://localhost:7687
